# +--------------------------------------------------------------------------------------------------------------------|
# |                                                                                           APP.Messages.telegram.py |
# |                                                                                             Author: Pauliv, Rômulo |
# |                                                                                          email: romulopauliv@bk.ru |
# |                                                                                                    encoding: UTF-8 |
# +--------------------------------------------------------------------------------------------------------------------|

# | Imports |----------------------------------------------------------------------------------------------------------|
import requests
from Tools.json.read_json import read_json
# |--------------------------------------------------------------------------------------------------------------------|

# | Params |-----------------------------------------------------------------------------------------------------------|
data: dict[str] = read_json("Services/credentials.json")
token: str = data["token"]
# |--------------------------------------------------------------------------------------------------------------------|

def send_message(chat_id: str, token: str, message: str) -> None:
    URL: str = f'https://api.telegram.org/bot{token}/sendMessage'

    params: dict[str] = {"chat_id": chat_id,
                         "text": message,
                         "parse_mode": "html"}
    try:
        requests.post(URL, params=params)
    except requests.exceptions.ConnectionError:
        pass

def telegram_booking_page() -> None:
    message: str = "❎ <b>Booking Alert</b> ❎\n\nThe AI has identified the booking page has been accessed!"\
    "\n\n⚠️ <b>LOGIN TO YOUR ACCOUNT NOW BITCH</b> ⚠️"
    
    send_message(data["admin_id"], token, message)
    send_message(data["client_id"], token, message)


def telegram_booking_alert() -> None:
    message: str = "⚠️ <b>Pop-up Alert</b>\n\nThe AI did not identify an 'unavailable service' pop-up in the booking loop.\n"\
    "This could be generated by instability in the network, host, or the <b>BOOKING WAS INITIATED</b>."\
        "\n\n⚠️ <b>We recommended logging into your account to verify</b> ⚠️"

    send_message(data["admin_id"], token, message)
    send_message(data["client_id"], token, message)


def telegram_login_info() -> None:
    message: str = "♨️ <b>Log in</b> ♨️\n\nYour account will be reconnected. Probably the host kicked your connection or there"\
    " is instability in the network.\n\nEverthing is ok 🧡"
    
    send_message(data["admin_id"], token, message)
    send_message(data["client_id"], token, message)